sudo: false
language: node_js
node_js:
  - "6"
  - "4"
install:
  - npm install
script:
  - npm run gulp -- ci
env:
  - CXX=g++-4.8 NODE_ENV=travis
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
